# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/KaszaLehel/index.json"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Restore packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    
    # --no-build
    - name: Pack Project
      run: dotnet pack --no-restore --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\output

    - name: Push Package
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}**/*.nupkg -k ${{ secrets.NUGET_SECRET }} --source https://nuget.pkg.github.com/KaszaLehel/index.json
    # ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    # - name: Test  ${{ env.NUGET_SOURCE_URL }}
    #   run: dotnet test --no-build --verbosity normal
    # -s https://nuget.pkg.github.com/[USERNAME]/index.json
